### ISSUE TITLE
Question - .Net Native AoT Support

### ISSUE THREAD

**Issue by Simonl9l** [extism/extism#167]
Hi just ran into this as am looking for Plugin management runtime solutions that support plugins developed different languages.

The host environment I'm developing in is .Net 7 - and we're looking to leverage _[Native AoT.](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/)_ 

Are there any pointers to whether `extism` will support both native AoT complied hosts, and in the case of .Net plugins those be native AoT compiled too ?

**Comment by nilslice** [comment]
Hi @Simonl9l - 

Please caveat the following with the fact that I am quite new to .NET, but I believe that a .NET AoT application _should_ be able to use Extism without issue. Extism is shipped as a library in C#, but is a wrapper over a system shared library (libextism.dll), which should be usable from an AoT compiled .NET program. 

In the case of .NET Extism plugins, those compile to WebAssembly, which is executed using [`wasmtime`]'s JIT embedded within Extism. These plugins compile to the WebAssembly binary format, instead of .NET IL -> native code. It is possible to further compile WebAssembly modules to native code, and we are exploring this - but it's not currently implemented. 

@mhmd-azeez, if you have some more detail here regarding the .NET Host being AoT compiled and working with Extism, please share :)

**Comment by mhmd-azeez** [comment]
Hi @nilslice @Simonl9l 

I did some experiments about running Extism in AOT mode.

### Hosts
For Hosts, AOT seems to somehow mess up our native calls. This might be because of some issue in our binding code. When I tried to call the `count_vowels` function, it blew up:

```
λ .\SampleHost.exe
Unhandled Exception: Extism.Sdk.Native.ExtismException: Call failed

Caused by:
    0: error while executing at wasm backtrace:
           0: 0xbf84f - <unknown>!<wasm function 447>
           1: 0xbbf5d - <unknown>!<wasm function 394>
           2: 0x65c1b - <unknown>!<wasm function 322>
           3: 0x61cdf - <unknown>!<wasm function 321>
           4: 0x36596a - <unknown>!<wasm function 6275>
           5: 0x20ee33 - <unknown>!<wasm function 3061>
           6: 0x210b1c - <unknown>!<wasm function 3077>
           7: 0x20f857 - <unknown>!<wasm function 3067>
           8: 0x40afb - <unknown>!<wasm function 145>
           9: 0xba9f5 - <unknown>!<wasm function 383>
          10: 0xb25e7 - <unknown>!<wasm function 322>
          11: 0x61cdf - <unknown>!<wasm function 321>
          12: 0x36596a - <unknown>!<wasm function 6275>
          13: 0x20ee33 - <unknown>!<wasm function 3061>
          14: 0x20ec01 - <unknown>!<wasm function 3059>
          15: 0x20ecfb - <unknown>!<wasm function 3060>
          16: 0x20ea38 - <unknown>!<wasm function 3057>
          17: 0x1458a5 - <unknown>!<wasm function 1442>
          18: 0x14550e - <unknown>!<wasm function 1440>
          19: 0x1453f7 - <unknown>!<wasm function 1439>
          20: 0x14781e - <unknown>!<wasm function 1458>
          21: 0xbd569 - <unknown>!<wasm function 404>
          22: 0x9bd07 - <unknown>!<wasm function 322>
          23: 0x61cdf - <unknown>!<wasm function 321>
          24: 0x36596a - <unknown>!<wasm function 6275>
          25: 0x20ee33 - <unknown>!<wasm function 3061>
          26: 0x210b1c - <unknown>!<wasm function 3077>
          27: 0x21a184 - <unknown>!<wasm function 3163>
          28: 0xe1d73 - <unknown>!<wasm function 703>
          29: 0xe1f98 - <unknown>!<wasm function 704>
          30: 0x35de - <unknown>!<wasm function 37>
          31: 0x4153a0 - <unknown>!<wasm function 7797>
    1: wasm trap: indirect call type mismatch
   at Extism.Sdk.Native.Plugin.CallFunction(String, ReadOnlySpan`1) + 0xa9
   at Program.<Main>$(String[]) + 0x102
   at SampleHost!<BaseAddress>+0x171d0b
```

### Plugins
For plugins, there seems to be some effort for AOT in wasm. But the efforts are all about [Blazor ](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-7.0#ahead-of-time-aot-compilation) currently. I tried the steps with [a sample extism pdk](https://github.com/mhmd-azeez/csharp-pdk/tree/restructure-projects) and it didn't seem to change the resulting `.wasm` file in any way.

But there seems to be some effort to bring LLVM (CoreRT) AOT to WASI. See [this ](https://github.com/dotnet/runtimelab/tree/feature/NativeAOT-LLVM) and [this](https://twitter.com/yowl00/status/1353421909749329920).

Overall, .NET's wasm/wasi support is experimental, but hopefully things will improve in the future .NET releases.

**Comment by bhelx** [comment]
Going to close this but we can keep any upstream updates here if anything new happens on the plugin side.
