### ISSUE TITLE
FR: Iterable Object for Functions

### ISSUE THREAD

**Issue by Bowbee** [extism/extism#207]
Hi,

It would be amazing to have an iterable object for the functions available to call on the wasm module.
The online playground does this to populate the dropdown but I believe it requires secondary files. If possible, loading from the  `.wasm` file would be amazing for schema checking and matching functions at runtime. 
Checking if a specific function exists on the wasm object is currently implemented, however creating an iterable opens this up further.

Keep up the great work,
Bowbee

**Comment by bhelx** [comment]
A note on this issue, apologies if we're late to respond. For the use case of validating the schema, I think modsurfer is the way to go as per @nilslice's comment here: https://github.com/extism/extism/pull/253#issuecomment-1421460462
It goes a lot deeper than just a list of functions. We should probably think a little more about how to more tightly integrate it with Extism, but note it can be run as a plugin.

> The online playground does this to populate the dropdown but I believe it requires secondary files.

For the browser runtime, we have a method `Plugin#getExports()` https://github.com/extism/extism/blob/main/browser/src/plugin.ts#L26
it just parses the wasm module and looks at the exports. We then filter them to guess at which ones might be extism functions:
https://github.com/extism/playground/blob/main/src/App.tsx

IMO it's more of an application level concern. Let's say your plugin has a list of "actions". You could, of course, export each action as a function. But instead of expecting the application to guess which functions are actions, you could provide another function to explicitly tell the application which actions it can take. For example, the signature could be something like: `getActions() -> Json<List<String>>` .

**Comment by nilslice** [comment]
@atifsyedali we have put some thought into this, and would really like to see a more community-led effort to build some tools / codegen around a protobuf / gRPC abstraction over the `Plugin.call` interface. 

Since our lower level APIs are simply bytes-in/bytes-out, you can already do protobuf across the SDK-PDK boundary. But to build a protoc plugin that generates the Plugin.call wrapper code would be very cool. 

Maybe we will spike something out, but if you're interested we'd love to help you.

**Comment by bhelx** [comment]
Just checking in here. Did a community member pick this up? If anyone is blocked by this i'd suggest using the modsurfer plugin to inspect the wasm as @nilslice mentioned here https://github.com/extism/extism/pull/253#issuecomment-1421460462
