### ISSUE TITLE
Maybe better naming and API interface?

### ISSUE THREAD

**Issue by AnharMiah** [extism/extism#327]
Hi team Extism,

I really like this project, and I think the dream of universal libraries that are _cross_ language is coming a lot closer because of projects like this!

Of course ideally languages supporting `WASM` directly would be the utopia. But until then Extism is a fantastic bridge.

The only thing that struck me is that the SDK for both the client AND the host could be less "boiler plate" and made simpler, it's my own strong opinion that most developers are super lazy, and the simpler you make something the more developers are likely to bother to use it.

So here is some pseudo code that I feel would attract more lazy developers to potentially use/adopt Extism:

## Host Side:

```javascript
const plugin = Extism.load("app.wasm");
const result = plugin.run("my_function", "{age: 10, name: 'bob'}");
console.log(result);
``` 

## Client/Plugin Side:

```kotlin
val input = Extism.input()
val myEnv = Extism.env("myEnv")
val name = Extism.get("name")
Extism.set("name", "fred") // setting a variable
Extism.return("hello friend!")
```

The above is what 90% of developers would want to see, they don't care for the low level details and boiler plate.

Also the library could also expose some of the finer "advanced" APIs so that those that need it can certainly use them as well.

**Comment by nilslice** [comment]
Hi @AnharMiah - 

Thank you for the kind words and the thoughtful suggestions here! We are always looking to improve upon the developer experience, and I agree that the APIs can improve and be more ergonomic. Your examples are nicely designed!

While nothing is perfect, we have decided on the APIs as they are for good reason (at least in my opinion :smile:). In order to support as many languages as possible, we've intentionally used lower level interfaces that can be implemented in the various C FFIs in the SDKs and PDKs across these languages. It's a tricky thing to do at all, and even trickier to keep all the languages capabilities and level of support in mind. 

I'd love to see some language-specific libraries built _on-top_ of our lower-level (more verbose + boilerplate) APIs, and would encourage you to build one using the design you've mentioned above! If it's helpful, I'll go through a couple of your ideas and explain why we didn't choose to make them our defaults though:

```js
const plugin = Extism.load("app.wasm");
```

While this is nice and simple, it implies that the user is always going to have their .wasm on disk, which is not always true. Many times .wasm is loaded over the network (via HTTP or a database or S3 etc.), or embedded into the program directly as bytes. Again, I think you could build a really nice utility library for Extism users in your language of choice, and the design you have could make some things more convenient. 

```js
const result = plugin.run("my_function", "{age: 10, name: 'bob'}");
```

This is actually the same interface we do expose for calling functions inside wasm from your program, so I must say, it's nice! We chose to call this method `call` though :) 

```js
val input = Extism.input()
```

Our API is not much different than this, although our default returns the raw bytes, vs. and encoded string (which is what I assume you'd want returned). The reason we don't always have a global `Extism` object like that is that in some PDK languages, we can't associate functions of an arbitrary object, so we have to design these based on the language primitives we have. If you'd like to make PRs to the various PDKs, please don't hesitate to do so!

```js
Extism.return("hello friend!")
```

I really like the idea of using `return` as a name here. However, it might be confusing since this wouldn't return from the function, and in many cases the PDK export functions actually need to explicitly return an error code int. So we chose the name `output` or something similar to indicate that you're setting the plugin's output back to the host environment. But, this definitely has us thinking and will consider it in the future. 

All that considered, I think the best approach here is for talented people like yourself to build higher-level libraries that wrap the Extism SDKs and PDKs to make more ergonomic utility functions and APIs for developers. 

I really appreciate your ideas here - and please keep them coming! Join us on Discord if you haven't already... happy to chat more about what you'd like to make and how we can help :)

https://discord.gg/cx3usBCWnc

**Comment by AnharMiah** [comment]
thanks @nilslice your explanation does makes sense, I suspect writing higher level wrappers might be the way to go, now the daunting task of writing wrappers in all the various languages! :sweat_smile:

**Comment by nilslice** [comment]
> now the daunting task of writing wrappers in all the various languages

:sweat_smile: indeed!
