### ISSUE TITLE
Async / Await / Generators / Coroutines in Plugins

### ISSUE THREAD

**Issue by vincent-lecrubier-skydio** [extism/extism#702]
Just discovered Extism today and it looks awesome!

One particular thing is missing for my use case: Support for Async / await / generators / coroutines in plugins. I don't see anything about this in the FAQ either. Have there been any thoughts about it?

**Comment by nilslice** [comment]
Hi! Thanks for the kind words 😃

Which PDK language are you looking at with those limitations? JS?

**Comment by vincent-lecrubier-skydio** [comment]
My main candidates for plugin languages are Python (doesn't exist yet, I know :-) ) with asyncio, JS with standard promises and generators, and Rust with tokio.

**Comment by YourTechBud** [comment]
I would like to add my usecase to this as well.

For me, my plugins need not be async. But they call a bunch of host functions which will be async. So technical the plugin would see all host functions as sync calls but the asynchronoucity would be powerful by the host's tokio runtime.

**Comment by bhelx** [comment]
This has been a tricky question for me because oftentimes, async / await does work at a syntax level in wasm, but not at a semantic level. The primary issue is wasm doesn't have the capability to support the underlying primitives just yet. There are some specs that [I think will address this](https://github.com/WebAssembly/stack-switching). but it may be a while before that makes it into all the runtimes and compilers.

In the meantime i definitely think we can do better and documenting what can be done and what can't. We're also working on encoding some common patterns people might have to deal with concurrency. Example: https://github.com/extism/extism/pull/696

For the time being, you can do things like @YourTechBud 's use case but you need to code it up yourself. Please share any experiences you have though, we'd love to formalize some more of these ideas.
