### ISSUE TITLE
allowlist WASI features/interfaces 

### ISSUE THREAD

**Issue by neuronicnobody** [extism/extism#719]
Is it possible to selectively enable certain WASI interfaces (e.g. clocks, file access) via Extism? For instance, I would want my plugins to be able to access the system clock via WASI but not access the filestystem

**Comment by bhelx** [comment]
Not sure i can give a completely general answer, but note that you shouldn't be able to access the filesystem just because you have WASI enabled. You still need to explicitly map which directories the guest can access. Same goes for the networking resources. You should be blocked by default unless the host explicitly says which domains can be accessed.
