### ISSUE TITLE
Host functions returning f32/f64 aren't working correctly

### ISSUE THREAD

**Issue by zshipko** [extism/extism#739]
From https://discord.com/channels/1011124058408112148/1050087728269766737/1260966340605513838:

> Plugin / c-pdk
typedef float f32;
EXTISM_IMPORT("test", "f32") extern f32 test_f32(f32);
/* ... */
#include <math.h>
f32 val = test_f32( (f32)-M_PI );
>
> Host / c-sdk
void test_f32(ExtismCurrentPlugin* plugin, const ExtismVal* inputs, ExtismSize n_inputs, ExtismVal* outputs, ExtismSize n_outputs, void* data) {
  outputs[0].v.f32 = inputs[0].v.f32;
}
/* ... */
ExtismValType types[] = { ExtismValType_F32 };
ExtismFunction* f = extism_function_new("f32", types, 1, types, 1, test_f32, 0, 0);
extism_function_set_namespace(f, "test");
>
> ... test_f32 seems to receive the f32 value correctly, but only ever return zero as output.

See https://gist.github.com/humbletim/e80ca56791a1add434d0ebfa64a7f146 for a reproduction of the issue.

Logging around the `extism::Function` inner calls ([here](https://github.com/extism/extism/blob/3a7768ffd5c209e41e12a80fc327c43cf4655bb9/runtime/src/function.rs#L216)) shows that the values are correct when the function returns.

**Comment by anlumo** [comment]
I'm pretty sure that this is due to some weird code I found while looking through the runtime:

https://github.com/extism/extism/blob/7b6664d019265fb2e61596f230f4bce152231209/runtime/src/sdk.rs#L269-L270

This isn't right. [Here is the documentation in wasmtime](https://docs.rs/wasmtime/25.0.2/wasmtime/enum.Val.html#variant.F32):

> Note that the raw bits of the float are stored here, and you can use `f32::from_bits` to create an `f32` value.
> Note that the raw bits of the float are stored here, and you can use `f64::from_bits` to create an `f64` value.

What struck me as weird there is that "`as u32`"/"`as u64`" just cuts off the non-integer part, so there has to be data loss there.

**Comment by zshipko** [comment]
Thank you @anlumo for catching that! Making this change seems to fix the reproduction I linked in the original issue! I have PR up here: https://github.com/extism/extism/pull/779 and will merge it once CI passes.
